### ISSUE TITLE
expected identifier or '(' before '}' token in gfx.c

### ISSUE THREAD

**Issue by ausera** [xtreme8000/CavEX#10]
![image](https://github.com/xtreme8000/CavEX/assets/84032091/53c9738d-1298-4537-ba53-01eb0ae463bd)

idk if i am compiling it wrong or missing a library.

**Comment by SmollestBug** [comment]
![export202308102143215397](https://github.com/xtreme8000/CavEX/assets/141927681/aca24d7b-be42-4419-bbc5-604c01c12db6)

Created this Github account to comment on this;
I've also had this compilation issue, I resolved it myself using Programmer's Notepad, but a series of warnings appear for several files after as seen in this screenshot, and the resulting .dol file opens to a black screen in the Homebrew Channel. (I did use the updated gfx.c from the repository to retry it before posting this.)

**Comment by xtreme8000** [comment]
The warnings are "fine".
Oh I should probably mention that latest devkitpro produces broken builds. They messed something up with `usleep()`, which now sleeps/hangs forever. While that function call can be removed and it will work without, performance will be severely degraded.

I use an older devkitpro version, unfortunately I have no idea how to downgrade it, because they remove older versions immediately from the pacman repo. Maybe there is a windows installer for an older version available.

**Comment by SmollestBug** [comment]
I managed to cobble together some older devkitPro install files from https://gbatemp.net/threads/collection-of-old-devkitpro-versions.526377/ and it seemingly has worked!
![Uploading export202308102257577386.png…]()
