### ISSUE TITLE
Unable to enter the nether

### ISSUE THREAD

**Issue by Alexis20000** [xtreme8000/CavEX#27]
When I light the fire via the lighter on the obsidian block to open the Nether portal there is no fire that lights up and on no other block as well which makes it impossible to enter in the Nether because even if we managed to set fire to the Obsidian block to open the dinosaur portal we would still not be able to go into the Nether because there is no animation of the portal which starts to move in all the senses and a few seconds later the screen starts loading which says that he is entering the Nether could you add a functional and accessible Nether
pls and when the Nether will be accessible could you give a Dol file and also all the files to make CavEx work pls

**Comment by Alexis20000** [comment]
You bitch

**Comment by Alexis20000** [comment]
This is not FUCKING INVALID

Impossible to access to the nether

**Comment by xtreme8000** [comment]
This is out of scope for this project, at least in singleplayer.

**Comment by toadragethe5th** [comment]
You can't just say that the nether portal doesn't work, and call the owner a bitch when he says that it's not feasible to put in. I'm guessing you aren't a programmer, because putting in a whole other dimension and rendering a separate world when you touch a certain block is incredibly complicated, especially in a low level language like C which isn't even originally meant for coding games.

**Comment by cheese-gaming** [comment]
> You bitch
> 

bro what? this port isnt done yet?
